### ISSUE TITLE
rosdep unable to install geographic-msgs and vision-msgs

### ISSUE THREAD

**Issue by Ryanf55** [alpine-ros/rosdistro#154]
I have a package that depends on geographic and vision messages. During my call to `rosdep install ...`, the following error is printed:

```
ERROR: unable to select packages:
  ros-humble-geographic-msgs (no such package):
    required by: world[ros-humble-geographic-msgs]
  ros-humble-vision-msgs (no such package):
    required by: world[ros-humble-vision-msgs]
```

If I try manually installing, I get the same error:
```
# apk add ros-humble-geographic-msgs
ERROR: unable to select packages:
  ros-humble-geographic-msgs (no such package):
    required by: world[ros-humble-geographic-msgs]
 ```
 
 Image: `ghcr.io/alpine-ros/alpine-ros:humble-3.17-ros-core`
 
 Most of the other message packages show up with the following command:
 ```
 apk search ros-humble*msgs
 ```

**Comment by f-fl0** [comment]
It seems the `geographic-msgs` package was missing for the `humble` distribution. I added it in https://github.com/seqsense/aports-ros-experimental/pull/859. It should be available shortly.

**Comment by f-fl0** [comment]
`geographic-msgs` should now be available.

**Comment by Ryanf55** [comment]
> `geographic-msgs` should now be available.

Sweet thanks! 
And `vision-msgs`, same story?

**Comment by f-fl0** [comment]
Sorry I will add it now.

**Comment by f-fl0** [comment]
`vision_msgs` is now also available.

**Comment by Ryanf55** [comment]
Thanks for the support!

This issue is now resolved. 

```
(317/319) Installing ros-humble-tf2-geometry-msgs (0.25.2-r0)
(318/319) Installing ros-humble-vision-msgs (4.1.0-r1)
```
